export const defaultConfig = {
  theme: 'none',
  zoom: '1.0',
  client_type: 'default',
  sys_tray: false,
  push_to_talk: false,
  push_to_talk_keys: ['RControl'],
  cache_css: false,
  use_native_titlebar: false,
  start_maximized: false,
  profile: 'default',
  streamer_mode_detection: false,
  rpc_server: false,
  open_on_startup: false,
  startup_minimized: false,
  autoupdate: false,
  update_notify: true,
  desktop_notifications: false,
  auto_clear_cache: false,
  multi_instance: false,
  disable_hardware_accel: false,
  blur: 'none',
  blur_css: true,
  client_mods: ['Shelter'],
  unread_badge: true,
}